// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// SwitchModelPrior
double SwitchModelPrior(Rcpp::NumericVector pVec);
RcppExport SEXP pda_SwitchModelPrior(SEXP pVecSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pVec(pVecSEXP);
    __result = Rcpp::wrap(SwitchModelPrior(pVec));
    return __result;
END_RCPP
}
// initializeStructures
Rcpp::List initializeStructures(const int nmc, const int npar, const int nchain);
RcppExport SEXP pda_initializeStructures(SEXP nmcSEXP, SEXP nparSEXP, SEXP nchainSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const int >::type nmc(nmcSEXP);
    Rcpp::traits::input_parameter< const int >::type npar(nparSEXP);
    Rcpp::traits::input_parameter< const int >::type nchain(nchainSEXP);
    __result = Rcpp::wrap(initializeStructures(nmc, npar, nchain));
    return __result;
END_RCPP
}
// getDTs
Rcpp::List getDTs(Rcpp::List data, Rcpp::NumericVector pVec, Rcpp::List MCMC_params);
RcppExport SEXP pda_getDTs(SEXP dataSEXP, SEXP pVecSEXP, SEXP MCMC_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pVec(pVecSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type MCMC_params(MCMC_paramsSEXP);
    __result = Rcpp::wrap(getDTs(data, pVec, MCMC_params));
    return __result;
END_RCPP
}
// logLik_fft
double logLik_fft(arma::vec DT, arma::vec eDT, double m, double M, double h, int ns);
RcppExport SEXP pda_logLik_fft(SEXP DTSEXP, SEXP eDTSEXP, SEXP mSEXP, SEXP MSEXP, SEXP hSEXP, SEXP nsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type DT(DTSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type eDT(eDTSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type M(MSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    __result = Rcpp::wrap(logLik_fft(DT, eDT, m, M, h, ns));
    return __result;
END_RCPP
}
// logLik_pLBA
double logLik_pLBA(Rcpp::List data, Rcpp::NumericVector pVec, Rcpp::List MCMC_params);
RcppExport SEXP pda_logLik_pLBA(SEXP dataSEXP, SEXP pVecSEXP, SEXP MCMC_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type data(dataSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pVec(pVecSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type MCMC_params(MCMC_paramsSEXP);
    __result = Rcpp::wrap(logLik_pLBA(data, pVec, MCMC_params));
    return __result;
END_RCPP
}
