# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Prior Log-likelihood
#'
#' This function computes the prior log-likelihood for the given parameter set,
#' using uniform distributions.
#'
#' @param pVec a vector storing pLBA model parameters. The sequence is 
#' critical. It is, A1, A2, v1, v2, t01, t02. 
#' @return a prior log prior likelihood
#' @export
#' @examples
#' logLik_prior(pVec)
#' 
logLik_prior <- function(pVec) {
    .Call('cpda_logLik_prior', PACKAGE = 'cpda', pVec)
}

#' @export
logLik_prior_test <- function(pVec) {
    .Call('cpda_logLik_prior_test', PACKAGE = 'cpda', pVec)
}

#' Generate a Gamma Vector 
#'
#' This is part of DEMC algorithm. \code{gammavec} generates a gamma vector 
#' for element-wise compuation in Armadillo C++.
#' 
#' @param npar number of parameters. 
#' @param gammamult a tuning parameter for gamma mutation. Default value is 
#' 2.38.
#' @return a column vector
#' @export
#' @examples
#' pVec <- c(A=1.51, b=2.7, muv1=3.32, muv2=2.24, t_ND=0.08, muw1=1.51,  
#'           muw2=3.69, t_delay=0.31,  sv=1, swt=0.5)
#' gamma <- gammavec(length(pVec), 2.38)
gammavec <- function(npar, gammamult = 2.38) {
    .Call('cpda_gammavec', PACKAGE = 'cpda', npar, gammamult)
}

#' Pick Other Chains Randomly
#'
#' This is part of DEMC algorithm. The function randomly samples \code{n}   
#' chains out of \code{length(chains)} chains, excluding the kth chain.
#' chains.
#'
#' @param k an integer indicating which chain is processed currently. This 
#' must be an integer within the range of 0 to \code{nchain-1} (i.e., C index).
#' No check for errorly using R index, because this is an internal function.
#' @param n the numbers of chain to sample.
#' @param chains a numeric vector of chain index, e.g., 0:24.  
#' @return a column vector
#' @keywords pickchains
#' @export
#' @examples
#' nchain <- 24
#' chainSeq <- (1:24)-1 ## Convert to C index
#' 
#' ## Current processing chain is the fourth chain (index=3) 
#' ## We wish to pick 2 chains out of 24 chains
#' pickchains(3, 2, chainSeq) 
#' 
pickchains <- function(k, n, chains) {
    .Call('cpda_pickchains', PACKAGE = 'cpda', k, n, chains)
}

#' Crossover and Migration Samplers    
#'
#' This is part of DE-MC algorithm (crossover) and Distributed Evolutionary 
#' Monte Carlo (migration). Both samplers propose a set of new parameters. 
#' 
#' @param theta a npar x nchain matrix 
#' @param gamma a gamma vector. 
#' @param k current chain index. Note chain index starts from 0.
#' @param rp ter Braak's (2006) b, setting the range of the uniform 
#' distribution that derives epsilon. This is set at 1e-3.
#' @return a column vector
#' @references ter Braak, C. J. F. (2006). A Markov Chain Monte Carlo version 
#' of the genetic algorithm Differerntial Evolution: Easy Bayesian computing
#' for real parameter spaces. Statistics and Computing, 16, 239–249. \cr\cr
#' Hu, B., & Tsui, K.-W. (2005). Distributed evolutionary Monte Carlo with 
#' applications to Bayesian analysis Technical Report Number 1112.
#' @export
#' @examples
#' init <- function(nc, npar) {
#'   theta0  <- array(dim = c(nc, npar))  
#'   theta0[,2] <- runif(nc, 0, 10);   # b
#'   theta0[,1] <- runif(nc, 0, theta0[,2]); # A
#'   theta0[,3] <- runif(nc, 0, 7);   # v1
#'   theta0[,4] <- runif(nc, 0, 7);   # v2
#'   theta0[,5] <- runif(nc, 0, .5)   # t0           
#'   return(theta0)
#' }
#' 
#' npar <- 5 
#' nc   <- npar * 1 
#' theta0  <- init(nc, npar)
#' gamma <- cpda::gammavec(npar, 2.38)
#'   
#' ## Current chain index is 0 (C-based index)
#' crossover(theta0, gamma, 0)
#' crossover(theta0, gamma, 1)
#' crossover(theta0, gamma, 2)
#' crossover(theta0, gamma, 3)
#' crossover(theta0, gamma, 4)
#' 
#' migration(theta0, gamma, 4)
#' get_subchains(nc)
#' 
crossover <- function(theta, gammamult = 2.38, rp = 0.001) {
    .Call('cpda_crossover', PACKAGE = 'cpda', theta, gammamult, rp)
}

#' @rdname crossover
#' @export
getsubchains <- function(nchain) {
    .Call('cpda_getsubchains', PACKAGE = 'cpda', nchain)
}

#' @rdname crossover
#' @export
migration <- function(theta, gammamult = 2.38, rp = 0.001) {
    .Call('cpda_migration', PACKAGE = 'cpda', theta, gammamult, rp)
}

#' @export
lik_fft <- function(y, yhat, h = 0, m = 0.8, p = 10, n = 0L) {
    .Call('cpda_lik_fft', PACKAGE = 'cpda', y, yhat, h, m, p, n)
}

#' Point-wise Probability Density Approximation
#'
#' \code{lik_pw} takes each observation and sequentially (or concurrently)
#' via Open MP) conduct KDEs. This function is for testing purpose. If you 
#' wish to conduct KDE smoothing point-by-point, use 'density'
#' in \code{stats}, which uses a similar FFT algorithm as \code{lik_fft}. 
#'
#' @param y a vector storing empirical observations (e.g., RTs).
#' @param yhat a vector storing simulations.
#' @param h kernel bandwidth. Default value is 0.8 times Silverman's Rule of
#' Thumb, based on simulated data (i.e., yhat).
#' @param m a bandwidth multiplier. Default is 0.8.
#' @param n the number of simulation. When n=0, where the function will count
#' the numbers of observation in the simulated histogram. If simulating 
#' a defective distribution, one should enter the simulation numbers. 
#' @param parallel a switch for parallel processing via OMP. Default is FALSE. 
#' @return a vector storing log-likelihoods
#' @references 
#' Holmes, W. (2015). A practical guide to the Probability Density
#' Approximation (PDA) with improved implementation and error characterization.
#' \emph{Journal of Mathematical Psychology}, vol. 68-69, 13--24,
#' doi: \url{http://dx.doi.org/10.1016/j.jmp.2015.08.006}. \cr
#' 
#' Turner, B. M. & Sederberg, P. B. (2014). A generalized, likelihood-free 
#' method for posterior estimation. \emph{Psychonomic Bulletin Review}, 21(2), 
#' 227-250. doi: \url{http://dx.doi.org/10.3758/s13423-013-0530-0}. \cr
#' 
#' Brown, S. & Heathcote, A. (2008). The simplest complete model of choice 
#' response time: Linear ballistic accumulation. \emph{Cognitive Psychology}, 
#' 57, 153-178. doi: \url{http://dx.doi.org/10.1016/j.cogpsych.2007.12.002}.
#' @export
#' @examples
#' ## Example 1 tests if Lik_pw match 'dnorm' and shows how to adjust 
#' ## bandwidth  
#' rm(list=ls())
#' lik_pw(0, rnorm(1e6)) ## 0.3974386
#' dnorm(0)              ## 0.3989423
#'
#' h <- 0.8*bw.nrd0(rnorm(1e6));            ## 0.04542646 
#' lik_pw(0, rnorm(1e6), h=h)      ## 0.3996198
#' lik_pw(0, rnorm(1e6), h=h, m=1) ## 0.3985692
#'
#' ## Example 2 demostrates how to use Lik_pw to get pLBA likelihoods
#' data(lba)
#' str(plba)
#' ## List of 4
#' ## $ DT1 : num [1:695] 0.488 0.801 0.376 0.507 0.532 ...
#' ## $ DT2 : num [1:305] 0.538 0.77 0.568 0.271 0.881 ...
#' ## $ eDT1: num [1:7020] 0.475 0.346 0.42 0.401 0.368 ...
#' ## $ eDT2: num [1:2980] 0.703 0.693 0.704 0.462 0.468 ...
#'
#' ## Use pointwise pda to get likelihoods for each data point
#' ## This algorithm calculates via a standard gaussian kernel directly
#' ## (1) First argument, plba$DT1, is the data.
#' ## (2) Second argument, plba$eDT1, is the simulation.
#' ## (3) The output is likelihood.
#'
#' output <- lik_pw(plba$DT1, plba$eDT1)
#' sum(output) ## Get summed, logged likelihood
#'
#' #########################
#' ## Example 3           ##
#' #########################
#' rm(list=ls())
#' n      <- 1e5
#' x      <- seq(-3,3, length.out=100) ## Support
#' xlabel <- "Observations" 
#' ylabel <- "Density" 
#' 
#' ## Approximate Gaussian densities
#' samp <- rnorm(n)
#' pw1  <- lik_pw(x, samp)
#' pw2  <- approx(density(samp)$x, density(samp)$y, x)$y
#' plot(x,  pw1, type="l", lty="longdash", xlab=xlabel, ylab=ylabel)
#' lines(x, pw2, lwd=1.5, lty="dotted")
#' lines(x, dnorm(x), lwd=2)
#' 
#' samp <- gamlss.dist::rexGAUS(n, mu=-2, sigma=1, nu=1)
#' system.time(pw1 <- lik_pw(x, samp, parallel=TRUE))
#' system.time(pw2 <- approx(density(samp)$x, density(samp)$y, x)$y)
#' plot(x,  pw1, type="l", lty="longdash", xlab=xlabel, ylab=ylabel)
#' lines(x, pw2, lwd=1.5, lty="dotted")
#' lines(x, gamlss.dist::dexGAUS(x, mu=-2, sigma=1, nu=1), col="red")
#'
#' ## Approximate densities of linear regression with Gaussian noise: 
#' ## y = ax + b + N(0, s)
#' theta <- c(a=7.5, b=3.5, s=5)
#' y     <- rnorm(length(x), mean=theta[2]+theta[1]*x, sd=theta[3])
#' dat   <- cbind(x, y)
#' plot(x, y, main="Linear Regression")
#' 
#' ## -- Because means for each data point differ, we need to generate 
#' ## simulation (ie samp) for each data point. That is, the likelihood for  
#' ## each data point is calculated by different simulated likelihood functions
#' ## -- We use sapply to gain a little speedy up. 
#' ## -- 'density' function cannot calculate density for only 1 data point 
#' pw1 <- sapply(x, function(s) {
#'   samp  <- rnorm(n, mean=theta[2]+theta[1]*s, sd=theta[3])
#'   lik_pw(s, samp)
#' })
#' plot(x,  pw1,  type="l", lty="longdash", xlab=xlabel, ylab=ylabel)
#' lines(x,  dnorm(x, theta[2]+theta[1]*x, theta[3]), col="red")
#' 
#' #########################
#' ## Example 4: LBA      ##
#' #########################
#' rm(list=ls())
#' ## Assuming that this is empirical data
#' y    <- rtdists::rLBA(1e3, A=.5, b=1, t0=.25, mean_v=c(2.4, 1.2), sd_v=c(1,1.2))
#' rt1  <- y[y$response==1,"rt"]
#' rt2  <- y[y$response==2,"rt"]
#' srt1 <- sort(rt1)
#' srt2 <- sort(rt2)
#' summary(rt1); summary(rt2)
#'     
#' n <- 1e5
#' pvec <- c(b=1, A=.5, v1=2.4, v2=1.2, sv1=1, sv2=1.2, t0=.25)
#' samp <- cpda::rlba1(n, pvec)
#' samp1 <- samp[samp[,2]==1, 1]
#' samp2 <- samp[samp[,2]==2, 1]
#' pw1 <- lik_pw(srt1, samp1, n=n)
#' pw2 <- lik_pw(srt2, samp2, n=n)
#'     
#' den0 <- rtdists::dLBA(y$rt, y$response, A=.5, b=1, t0=.25, 
#'   mean_v=c(2.4, 1.2), sd_v=c(1, 1.2))
#' df0 <- cbind(y, den0)
#' df1 <- df0[df0[,2]==1,]
#' df2 <- df0[df0[,2]==2,]
#' den1 <- df1[order(df1[,1]),3]
#' den2 <- df2[order(df2[,1]),3]
#'   
#' plot(srt1,  den1, type="l")
#' lines(srt2, den2)
#' lines(srt1, pw1, col="red")
#' lines(srt2, pw2, col="red")
#'     
#' #########################
#' ## Example 5           ##
#' #########################
#' n   <- 1e5
#' x   <- seq(-3,3, length.out=100) ## Support
#' sam <- rnorm(n)
#' 
#' ## Tested on 12-core CPU
#' rbenchmark::benchmark(replications=rep(10, 3),
#'    pw       <- cpda::lik_pw(x, sam),
#'    pw_omp   <- cpda::lik_pw(x, sam, parallel = T),
#'    columns=c('test', 'elapsed', 'replications'))
#' ##                                           test elapsed replications
#' ## 1                   pw <- cpda::lik_pw(x, sam)   2.570           10
#' ## 3                   pw <- cpda::lik_pw(x, sam)   2.485           10
#' ## 5                   pw <- cpda::lik_pw(x, sam)   2.484           10
#' ## 2 pw_omp <- cpda::lik_pw(x, sam, parallel = T)   0.993           10
#' ## 4 pw_omp <- cpda::lik_pw(x, sam, parallel = T)   1.119           10
#' ## 6 pw_omp <- cpda::lik_pw(x, sam, parallel = T)   1.024           10
#' 
#' @export
lik_pw <- function(y, yhat, h = 0, m = 0.8, n = 0L) {
    .Call('cpda_lik_pw', PACKAGE = 'cpda', y, yhat, h, m, n)
}

#' @export
n1PDF <- function(x, nsim, b, A, mean_v, sd_v, t0, k = 0.09) {
    .Call('cpda_n1PDF', PACKAGE = 'cpda', x, nsim, b, A, mean_v, sd_v, t0, k)
}

#' @export
timesTwo <- function(x) {
    .Call('cpda_timesTwo', PACKAGE = 'cpda', x)
}

#' Truncated Normal Distribution
#'
#' Three functions implementing random number generator, density function and
#' cumulative distribution function (\code{rtn}, \code{dtn}, and \code{ptn})
#' for truncation normal distribution.
#'
#' @param x,n,q x in \code{dtn} is a vector of quantiles; n in \code{rtn}
#' is number of observations. n must be a scalar. q is a vector of quantiles.
#' @param mean mean (must be scalar).
#' @param sd standard deviation (must be scalar).
#' @param lower lower truncation value (must be scalar).
#' @param upper upper truncation value (must be scalar).
#' @param lt lower.tail. a boolean switch; if TRUE (default) probabilities are
#' \code{P[X <= x]}, otherwise, \code{P[X > x]}.
#' @param lp log.p. a boolean switch; if TRUE (default is FALSE) probabilities p
#' are given as \code{log(p)}.
#' @return a column vector.
#' @examples
#' ## rtn example
#' dat1 <- rtn(1e5, 0, 1, 0, Inf)
#' ## dat2 <- msm::rtnorm(n, mean, sd, lower, upper)
#' ## den2 <- density(dat2)
#' hist(dat1, breaks="fd", freq=F)
#' ## lines(den2$x, den2$y, lwd=2.5)
#' ## res <- microbenchmark(
#' ##     rtn(n, mean, sd, lower, upper),
#' ##     msm::rtnorm(n, mean, sd, lower, upper))
#' ## print(res)
#'
#' ## dtn example
#' x <- seq(-5, 5, length.out=1e3)
#' dat1 <- dtn(x, 0, 1, -2, 2, 0)
#' ## dat2 <- msm::dtnorm(x, mean, sd, lower, upper, 0)
#' plot(x, dat1, type="l", lwd=2)
#' ## lines(x, dat2, lwd=2, lty="dashed", col="red")
#'
#' ## res <- microbenchmark(
#' ##     dtn(x, mean, sd, lower, upper, 0),
#' ##     msm::dtnorm(x, mean, sd, lower, upper, 0))
#' ## print(res)
#'
#' ## ptn example
#' x <- seq(-50, 10, length.out=1e3)
#' mean <- 0
#' sd <- 1
#' lower <- 0
#' upper <- 5
#' dat1 <- ptn(x, 0, 1, 0, 5, lp=TRUE)
#' ## dat2 <- msm::ptnorm(x, mean, sd, lower, upper, log.p=TRUE)
#' ## all(dat1[,1] == dat2)
#'
#' plot(x, log(dat1[,1]))
#' ## lines(x, log(dat2), col="red", lwd=2)
#' ## mtext("pnorm(x, log=TRUE)", adj = 0)
#' ## mtext("log(pnorm(x))", col = "red", adj = 1)
#' @export
dtn <- function(x, mean, sd, lower, upper, lp = FALSE) {
    .Call('cpda_dtn', PACKAGE = 'cpda', x, mean, sd, lower, upper, lp)
}

#' @rdname dtn
#' @export
rtn <- function(n, mean, sd, lower, upper) {
    .Call('cpda_rtn', PACKAGE = 'cpda', n, mean, sd, lower, upper)
}

#' @rdname dtn
#' @export
ptn <- function(q, mean, sd, lower, upper, lt = TRUE, lp = FALSE) {
    .Call('cpda_ptn', PACKAGE = 'cpda', q, mean, sd, lower, upper, lt, lp)
}

#' @export
rlba <- function(n, b, A, mean_v, sd_v, t0) {
    .Call('cpda_rlba', PACKAGE = 'cpda', n, b, A, mean_v, sd_v, t0)
}

#' @export
rlba_n1 <- function(n, b, A, mean_v, sd_v, t0) {
    .Call('cpda_rlba_n1', PACKAGE = 'cpda', n, b, A, mean_v, sd_v, t0)
}

#' A simple and fast quantile calculator
#'
#' A C++ quantile function.
#'
#' @param y a data vector
#' @param q nth quantile. Enter proportion, such as .25 or .75.
#' @examples
#' y <- rnorm(100)
#' q <- cquantile(y, .25)
#' @export
cquantile <- function(y, q) {
    .Call('cpda_cquantile', PACKAGE = 'cpda', y, q)
}

#' Silverman's Rule of Thumb Bandwidth for Kernel Density Estimation
#'
#' A C++ version of Silverman's rule-of-thumb bandwidth. This is similar
#' with R's \code{bw.nrd0(x)}
#'
#' @param y a data vector
#' @param m a multiplier to adjust the SROT proportionally.
#'
#' @seealso
#' \code{\link{bw.nrd}}, \code{\link{bandwidth.nrd}}.
#' @export
#' @examples
#' data(lba)
#' h <-cpda::bwNRD0(plba$DT1, 0.8)
#'
bwNRD0 <- function(y, m) {
    .Call('cpda_bwNRD0', PACKAGE = 'cpda', y, m)
}

#' @export
histc <- function(x, edge) {
    .Call('cpda_histc', PACKAGE = 'cpda', x, edge)
}

#' @export
histd <- function(yhat, z, n) {
    .Call('cpda_histd', PACKAGE = 'cpda', yhat, z, n)
}

#' Calculate Histogram Edges 
#'
#' This is an internal function. The user may not use it.
#' 
#' @param z a grid a scalar, usually created by 
#' \code{z = arma::linspace<arma::vec>(z0, z1, 1<<(int)p);}
#' 
#' @examples
#' set.seed(123)
#' dat1 <- stats::rnorm(1e2)
#' h  <- bw.nrd0(dat1)
#' z0 <- min(dat1) - 3*h 
#' z1 <- max(dat1) + 3*h
#' ngrid <- 2^10
#' dt <- (z1 - z0) / (ngrid - 1)
#' z  <- z0 + (0:(ngrid-1)) * dt
#' ## Same as using seq function
#' ## seq(z0, z1, length.out=ngrid)
#' 
#' binedge1 <- c(z - 0.5*dt, z[ngrid] + 0.5*dt)
#' binedge2 <- as.vector(cpda::getEdges(z))
#' all.equal(binedge1, binedge2)
#' mean(binedge - as.vector(tmp))
#' ## [1] 2.640334e-17
#' 
#' ## 4.00 vs. 14.1 microseconds
#' ## library(microbenchmark)
#' ## res <- microbenchmark(
#' ##    binedge1 <- c(z - 0.5*dt, z[ngrid] + 0.5*dt),
#' ##    binedge2 <- as.vector(cpda::getEdges(z)),
#' ##   times=10L)
#' @export
getEdges <- function(z) {
    .Call('cpda_getEdges', PACKAGE = 'cpda', z)
}

#' @export
getFilter <- function(m, M, h, p) {
    .Call('cpda_getFilter', PACKAGE = 'cpda', m, M, h, p)
}

