# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Summed Log-likelihood for a Gaussian Distribution
#'
#' This is a wrapper function to approximate a Gaussian distribution, using
#' KDE-FFT method. To retrieve more outputs, use \code{logLik_norm2}.
#'
#' \code{logLik_norm2} is identical to \code{logLik_norm}, except returning 
#' four elements:
#' 
#' \itemize{
#' \item \bold{\emph{LL}}, summed, logged likelihood. This is the same as the 
#' return value from \code{logLik_plba}. 
#' \item \bold{\emph{PDF}}, a numeric vector storing \emph{logged} 
#' probability densities for individual data point.
#' \item \bold{\emph{z}}, a numeric vector storing centre points of the 
#' simulated histogram (i.e., grid centre)
#' \item \bold{\emph{PDF_hist}} a numeric vector stoing the count of simulated
#' data point in each bin 
#' } 
#' @param object a vector storing empirical data
#' @param pVec parameter vector storing mean and standard deviation
#' @param ns number of simulations. 
#' @param h KDE bandwidth. If not input been enter, the default is 
#' Sliverman's rule of thumb; otherwise the function uses the input from
#' the user; 
#' @param m a multiplier to adjust proportationally h. Default is 0.8
#' @param p a precision parameter defines the number of grid as power of 2.
#' Default value is 10 (i.e., 2^10).
#' @return Log-likelihood; plus PDF, grid centers, and PDF_hist
#' @export
#' @examples
#' pVec <- c(mu=5, sigma=1)
#' y    <- sort(rnorm(1e5, pVec[1], pVec[2]))
#'
#' ll1 <- logLik_norm(y, pVec, 1e5)
#' ll2 <- logLik_norm2(y, pVec, 1e5)
#' str(ll1); str(ll2)
#'
#' plot(ll2$z, ll2$PDF_hist, type="l", lty=2,
#' main="Normal Distribution",xlab="x",ylab="L(x|theta)")
#' lines(y, exp(ll2$PDF), col="red", lwd = 1.5)
#'
logLik_norm <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_norm', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' @rdname logLik_norm
#' @export
logLik_norm2 <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_norm2', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' Compute Summed Log-likelihood for a pLBA Model
#'
#' This is a wrapper function to approximate a pLBA distribution, using
#' KDE-FFT method. To retrieve more outputs, use \code{logLik_plba2}.
#'
#' \code{logLik_plba2} is identical to \code{logLik_plba}, except returning 
#' four elements:
#' 
#' \itemize{
#' \item \bold{\emph{LL}}, summed, logged likelihood. This is the same as the 
#' return value from \code{logLik_plba}. 
#' \item \bold{\emph{PDF}}, a numeric vector storing \emph{logged}  
#' probability densities for individual data point.
#' \item \bold{\emph{z}}, a numeric vector storing centre points of the 
#' simulated histogram (i.e., grid centre)
#' \item \bold{\emph{PDF_hist}} a numeric vector stoing the count of simulated
#' data point in each bin 
#' } 
#' 
#' @param object a matrix storing empirical choice RT data. First column must
#' stores choices and second column stores RTs in seconds.
#' @param pVec a vector storing pLBA model parameters. The sequence is 
#' critical. It is, A, b, muv1, muv2, t_ND, muw1, muw2, t_delay, sv, swt. 
#' @param ns number of simulations. Usually \code{cpda} can handle up to 1e6. 
#' Use \code{gpda} if large simulation is required.
#' @param h KDE bandwidth. If not input been enter, the default is 
#' Sliverman's rule of thumb; otherwise the function uses the input from
#' the user; 
#' @param m a multiplier to adjust proportationally h. Default is 0.8
#' @param p a precision parameter defines the number of grid as power of 2.
#' Default value is 10 (i.e., 2^10).
#' @return a summed, logged likelihood across trials and accumulators. 
#' \code{logLik_plba2} returns three more elements.
#' @export
#' @examples  
#' ###################
#' ## Example 1     ##
#' ###################
#' ## I demonstrate how to use the build-in logLik_plba to calculate
#' ## pLBA densities. set.seed(123) is to produce the same result.
#' rm(list=ls())
#' pVec <- c(A=1.51, b=2.7, muv1=3.32, muv2=2.24, t_ND=0.08, muw1=1.51, 
#'           muw2=3.69, t_delay=0.31, sv=1, swt=0.5)
#'           
#' data(lba)
#' dMat <- data.matrix(d); head(dMat)
#' 
#' set.seed(123)
#' samp   <- cpda::rplba(1e5, pVec); head(samp)
#' h   <- 0.8*bw.nrd0(samp[,2]); h
#' set.seed(123)
#' ll0 <- cpda::logLik_plba(dMat, pVec, 1e5, h=h, m=1); ll0
#' ## [1] -7254.58
#' set.seed(123)
#' llList <- cpda::logLik_plba2(dMat, pVec, 1e5, h=h, m=1); 
#' str(llList)
#' 
#' ## List of 4
#' ## $ LL      : num -7255
#' ## $ PDF     : num [1:1000, 1] -23 -23 -23 -23 -23 ...
#' ## $ z       : num [1:2048, 1] 0.175 0.179 0.184 0.188 0.192 ...
#' ## $ PDF_hist: num [1:2048, 1] 0 0 0 0 0 0 0 0 0 0 ...
#' 
#' ## Here I demonstrate use rplba and logLik_fft to produce identical 
#' ## result
#' set.seed(123)
#' samp   <- cpda::rplba(1e5, pVec); head(samp)
#' DTMat  <- cpda::choiceDT(dMat, pVec)
#' time1  <- sort(DTMat[DTMat[,1] == 1, 2])
#' time2  <- sort(DTMat[DTMat[,1] == 2, 2])
#' time1_ <- sort(samp[samp[,1] == 1, 2])
#' time2_ <- sort(samp[samp[,1] == 2, 2])
#' ll1 <- cpda::logLik_fft(time1, time1_, h=h, m=1); ll1 ## [1] -5492.192
#' ll2 <- cpda::logLik_fft(time2, time2_, h=h, m=1); ll2 ## [1] -1762.388
#' print(ll1+ll2)
#' ## [1] -7254.58
#'          
logLik_plba <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_plba', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' @rdname logLik_plba
#' @export
logLik_plba2 <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_plba2', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' Compute Summed Log-likelihood for a LBA Model
#'
#' This is a wrapper function to approximate the densities of a LBA model, 
#' using \code{logLik_fft}. To retrieve more outputs, use \code{logLik_lba2}.
#' 
#' \code{logLik_lba2} is identical to \code{logLik_lba}, except the former 
#' returns three more elements: 
#'  
#' \itemize{
#' \item \bold{\emph{LL}}, summed, logged likelihood. This is the same as the 
#' return value from \code{logLik_lba}. 
#' \item \bold{\emph{PDF}}, a numeric vector storing logged probability 
#' densities for individual data point.
#' \item \bold{\emph{z}}, a numeric vector storing centre points of the 
#' simulated histogram (i.e., grid centre)
#' \item \bold{\emph{PDF_hist}} a numeric vector stoing the count of simulated
#' data point in each bin 
#' } 
#'
#' @param object a matrix storing empirical choice RT data. First column must
#' be choices (1 & 2) and second column must bve RTs in seconds.
#' @param pVec LBA parameter vector. The sequence is critical. It is b1, b2, 
#' A1, A2, mu1, mu2, sigma1, sigma2, t01, and t02. 1 and 2 stand for 
#' accumulator 1 and 2, respectively.  
#' @param ns number of simulations.  
#' @param h KDE bandwidth. If not given, the default \code{h} is 
#' Sliverman's rule of thumb; otherwise the function uses the input from
#' the user; 
#' @param m a multiplier to adjust proportationally h. Default is 0.8
#' @param p a precision parameter defines the number of grid as power of 2.
#' Default value is 10 (i.e., 2^10).
#' @return a summed, logged likelihood across trials and accumulators. 
#' \code{logLik_plba2} returns three more elements.
#' @export
#' @examples  
#' ## Demo identical outputs from manually building rlba and logLik_fft, 
#' ## comparing to logLik_lba 
#' 
#' ## First retrieve example data set
#' data(lba)  
#' d$R <- ifelse(d$Response==0, 1, 2)  ## convert 0 & 1 accumulator to 1 & 2
#' dMat <- data.matrix(data.frame(R=d$R, RT=d$ResponseTime))
#' head(dMat)
#'  
#' ## LBA parameter vector. The sequence is critical. 
#' pVec <- c(b1=1, b2=1, A1=.5, A2=.5, mu1=2.4, mu2=1.6, sigma1=1, sigma2=1.2,
#'           t01=.5, t02=.5)
#'            
#' set.seed(123)  ## make sure using identical simulations
#' samp <- cpda::rlba(1e5, pVec); head(samp)
#' h    <- 0.8*bw.nrd0(samp[,2]); h
#' 
#' ## logLik_lba simulates internally, so set.seed ahead to make sure using
#' ## identical simulations
#' set.seed(123)  
#' tmp0 <- cpda::logLik_lba(dMat, pVec, 1e5, h, 1); tmp0 ## -3496.88
#' 
#' ## Manually calculate empirical DTs for accumulator 1 and accumualtor 2
#' dt1  <- sort(dMat[dMat[,1] == 1, 2]) - pVec[9]
#' dt2  <- sort(dMat[dMat[,1] == 2, 2]) - pVec[10]
#' dt1_ <- sort(samp[samp[,1] == 1, 2]) - pVec[9]
#' dt2_ <- sort(samp[samp[,1] == 2, 2]) - pVec[10]
#'     
#' ## Calculating log-likelihoods separately for each accumulator
#' ll1 <- cpda::logLik_fft(dt1, dt1_, h, 1); ll1
#' ll2 <- cpda::logLik_fft(dt2, dt2_, h, 1); ll2
#' print(ll1+ll2) ## -3496.88
#'  
logLik_lba <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_lba', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' @rdname logLik_lba
#' @export
logLik_lba2 <- function(object, pVec, ns, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_lba2', PACKAGE = 'cpda', object, pVec, ns, h, m, p)
}

#' Compute Summed Log-Likelihood Using KDE-FFT 
#'
#' This function uses KDE-FFT method to approximate probability density. 
#' \code{logLik_fft} returns only one scalar value, which is summed, logged 
#' likelihood. Use \code{logLik_fft2} to retrieve three additional elements: 
#' \emph{PDF}, \emph{z} and \emph{PDF_hist}. See \code{\link{logLik_fft2}} for 
#' further details.  
#'
#' @param y a scalar or vector storing empirical data.
#' @param yhat a scalar or vector storing simulated data (e.g., 
#' \code{rnorm(100)}).
#' @param h the bandwidth of kernel density estimation. If not given, 
#' \code{logLik_fft} will detect the default, \code{h==0} and accordingly 
#' convert it to Sliverman's rule of thumb; otherwise the function uses 
#' bandwidth entered by the user; 
#' @param m a multiplier to adjust \code{h} proportationally. Default is 0.8. 
#' If one wish not adjust bandwidth, s/he has to enter \code{m=1}. 
#' @param p a precision parameter defines the number of grid as power of 2.
#' Default value is 10 (i.e., ngrid==2^10). 
#' @return Summed log-likelihood
#' @references Holmes, W. (2015). A practical guide to the Probability Density
#' Approximation (PDA) with improved implementation and error characterization.
#' \emph{Journal of Mathematical Psychology}, \bold{68-69}, 13--24,
#' doi: http://dx.doi.org/10.1016/j.jmp.2015.08.006.
#' @seealso
#' \code{\link{bw.nrd}}, \code{\link{logLik_fft2}}, 
#' \code{\link{bandwidth.nrd}}.
#' 
#' @export
#' @examples
#' ## See logLik_fft2 for more examples
#' ## Use piecewise LBA data as an example
#' data(lba)
#' logLik_fft(plba$DT1, plba$eDT1)
#' logLik_fft(plba$DT2, plba$eDT2)
logLik_fft <- function(y, yhat, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_fft', PACKAGE = 'cpda', y, yhat, h, m, p)
}

#' Compute Summed Log-Likelihood and Return Likelihoods for Each Data Point  
#'
#' This function is identical to \code{logLik_fft}, except returning more
#' elements. Unlike \code{logLik_pw} calculates directly Gaussian kernel
#' (see p. 14, eq. 1.2 in Holmes, 2015), \code{logLik_fft2} and 
#' \code{logLie_fft},  
#' \enumerate{
#' \item takes Monte Carlo simulations,
#' \item transforms them to spectral domain using FFT,
#' \item applies Gaussian kernel to smooth them,
#' \item transforms them back to signal domain and
#' \item interpolates linearly the simulation density/histogram to the observed data 
#' points to obtain estimated likelihoods.
#' }
#'  
#' \code{logLik_fft2} returns four elements:
#' \itemize{
#' \item \bold{\emph{LL}}, summed, logged likelihood. This is the same as the 
#' return value from \code{logLik_fft}. 
#' \item \bold{\emph{PDF}}, a numeric vector storing logged probability 
#' densities for individual data point.
#' \item \bold{\emph{z}}, a numeric vector storing centre points of the 
#' simulated histogram (i.e., grid centre)
#' \item \bold{\emph{PDF_hist}} a numeric vector stoing the count of simulated
#' data point in each histogram bin 
#' } 
#'
#' @param y a scalar or vector storing empirical data.
#' @param yhat a scalar or vector storing simulated data (e.g., 
#' \code{rnorm(100)}).
#' @param h the bandwidth of kernel density estimation. If not given, 
#' \code{logLik_fft} will use Sliverman's rule of thumb; otherwise the 
#' function uses the input from the user; 
#' @param m a multiplier to adjust \code{h} proportationally. Default is 0.8. 
#' This applies also when one enters his/her own bandwidth. So if one wish 
#' not to adjust bandwidth, enter \code{m=1}. 
#' @param p a precision parameter defines the number of grid as power of 2.
#' Default value is 10 (i.e., 2^10). 
#' @return A list with 4 elements.
#' @references Holmes, W. (2015). A practical guide to the Probability Density
#' Approximation (PDA) with improved implementation and error characterization.
#' \emph{Journal of Mathematical Psychology}, \bold{68-69}, 13--24,
#' doi: http://dx.doi.org/10.1016/j.jmp.2015.08.006.
#' @seealso
#' \code{\link{logLik_pw}}, \code{\link{logLik_fft}},
#' \code{\link{bw.nrd}}, \code{\link{bandwidth.nrd}}.
#' 
#' @export
#' @examples
#' ###################
#' ## Example 1     ##
#' ###################
#' x <- seq(-3, 3, length.out=100) ## Data
#' samp <- rnorm(1e6)              ## Monte Carlo simulation 
#' h <- 0.8*bw.nrd0(samp)          ## Define bandwidth using R's bw.nrd0
#' 
#' ## First, I demonstrate how to use point-wise logLik
#' ## Note logLik_pw returns log-likelihood.
#' system.time(pw1  <- logLik_pw(x, samp, h=h, m=1))
#' ##   user  system elapsed 
#' ##  3.480   0.120   3.605 
#' 
#' ## Second, I demonstrate how to use KDE-FFT. logLik_fft2 retrieves 
#' ## log-likelihoods for all data point  
#' system.time(fft1 <- logLik_fft2(x, samp, h=h, m=1)[["PDF"]])
#' ##   user  system elapsed 
#' ##  1.056   0.024   1.079 
#' 
#' ## Third, I demonstrate how to build-in routine binding logLik_fft and 
#' ## rnorm to get Gaussian density. Enter ?logLik_norm2 to see help page
#' ## pVec stands for parameter vector. For a Gaussian model, pVec stores mean
#' ## and standard deviation.
#' system.time(fft2 <- logLik_norm2(x, pVec=c(0,1), 1e6, h=h, m=1)[["PDF"]])
#' ##   user  system elapsed 
#' ##  1.304   0.040   1.349  
#' 
#' ## You should get all 4 lines overlaping one another
#' ## the tails may be a bit off.
#' plot(x, pw1,type="l", lty="dotted")
#' lines(x, fft1, col="darkgreen", lty="dashed")
#' lines(x, fft2, col="blue", lty="dotdash")
#' lines(x, dnorm(x, log=TRUE), col="red")
#' 
#' ###################
#' ## Example 2     ##
#' ###################
#' ## Use piecewise LBA data as an example
#' data(lba)
#' logLik_fft(plba$DT1, plba$eDT1)
#' logLik_fft(plba$DT2, plba$eDT2)
#' plbaEg1 <- logLik_fft2(plba$DT1, plba$eDT1)
#' plbaEg2 <- logLik_fft2(plba$DT2, plba$eDT2)
#'
#' str(plbaEg1)
#' ## List of 4
#' ## $ LL      : num 280
#' ## $ PDF     : num [1:695, 1] 0.918 -0.456 0.668 0.872 0.788 ...
#' ## $ z       : num [1:1024, 1] 0.128 0.129 0.13 0.131 0.133 ...
#' ## $ PDF_hist: num [1:1024, 1] 0 0 0 0 0 0 0 0 0 0 ...
#' str(plbaEg2)
#' ## List of 4
#' ## $ LL      : num 45.3
#' ## $ PDF     : num [1:305, 1] 0.6396 -0.1174 0.6178 -1.3723 -0.0273 ...
#' ## $ z       : num [1:1024, 1] 0.121 0.124 0.126 0.129 0.131 ...
#' ## $ PDF_hist: num [1:1024, 1] 0 0 0 0 0 0 0 0 0 0 ...
logLik_fft2 <- function(y, yhat, h = 0, m = 0.8, p = 10) {
    .Call('cpda_logLik_fft2', PACKAGE = 'cpda', y, yhat, h, m, p)
}

#' Generate Random Choice Response Times Using LBA Model
#'
#' This function uses two-accumulator LBA model to generate random choice RTs.
#' 
#' \itemize{
#' \item \bold{\emph{b1}} response threshold for accumulator 1. 
#' \item \bold{\emph{b2}} response threshold for accumulator 2. 
#' \item \bold{\emph{A1}} starting point interval for accumulator 1. 
#' \item \bold{\emph{A2}} starting point interval for accumulator 2. 
#' \item \bold{\emph{mu1}} drift rate for accumulator 1.
#' \item \bold{\emph{mu2}} drift rate for accumulator 2. 
#' \item \bold{\emph{sigma1}} drift rate standard deviation for accumulator 1.
#' \item \bold{\emph{sigma2}} drift rate standard deviation for accumulator 2.
#' \item \bold{\emph{t01}} non-decision time for accumulator 1. 
#' \item \bold{\emph{t02}} non-decision time for accumulator 2. 
#' }
#'
#' @param n number of observations. Must be an integer
#' @param pVec a two-accumulator LBA parameter vector. The sequence is 
#' critical. It is, b1, b2, A1, A2, mu1, mu2, sigma1, sigma2, t01, and t02.
#' @return A matrix. First column stores choices and second column stores RTs 
#' in seconds
#' @export
#' @examples
#' n    <- 10
#' pVec <- c(b1=1, b2=1, A1=.5, A2=.5, mu1=2.4, mu2=1.6, sigma1=1, sigma2=1.2,
#'           t01=.5, t02=.5)
#' dat1 <- cpda::rlba(n, pVec)
#' str(dat1)
#' summary(dat1)
#' 
#' ## Compare to rtdists
#' ## dat2 <- rtdists::rLBA(n, A=0.5, b=1, t0 = 0.5, mean_v=c(2.4, 1.6), 
#' ## sd_v=c(1,1.2))
#' ## str(dat2)
#' ## summary(dat2)
#' 
rlba <- function(n, pVec) {
    .Call('cpda_rlba', PACKAGE = 'cpda', n, pVec)
}

#' Generate Random Choice Decision Times using pLBA Model
#'
#' This function use two-accumulator piecewise LBA model to generate random 
#' choice DTs (not RTs!). A parallel version \code{rplba_omp} enables parallel 
#' random-number generation (used when n > 1e6).
#' 
#' \itemize{
#' \item \bold{\emph{A}} start point interval. \code{A} is the upper bound 
#' of the interval \code{[0, A]}. An uniform distribution with bound, 
#' \code{[0, A]} is used to generated a start point. Average amount of prior 
#' evidence (ie before accumulation process even begins) across trials is 
#' \code{A/2}. 
#' \item \bold{\emph{b}} response threshold. \code{b-A/2} is a measure of 
#' average \emph{response caution}.
#' \item \bold{\emph{muv1}} accumulator 1 drift rate, stage 1
#' \item \bold{\emph{muv2}} accumulator 2 drift rate, stage 1
#' \item \bold{\emph{t_ND}} non-decision time in second. 
#' \item \bold{\emph{muw1}} accumulator 1 drift rate, stage 2
#' \item \bold{\emph{muw2}} accumulator 2 drift rate, stage 2
#' \item \bold{\emph{t_delay}} delay time for the two-stage process   
#' \item \bold{\emph{sv}} a common standard deviation for all drift rates 
#' (muv1, muw1, muv2, muw2).
#' \item \bold{\emph{swt}} switch time, usually determined by experimental 
#' design.
#' }
#'
#' @param n number of observations. Must be an integer 
#' @param pVec a double vector storing pLBA model parameters. The sequence is 
#' critical. It is, A, b, muv1, muv2, t_ND, muw1, muw2, t_delay, sv, swt. 
#' @return A n x 2 matrix with a first column storing choices and second 
#' column storing DTs.
#' @export
#' @examples
#' ## pVec stands for parameter vector
#' pVec <- c(A=1.51, b=2.7, muv1=3.32, muv2=2.24, t_ND=0.08, muw1=1.51, 
#'           muw2=3.69, t_delay=0.31, sv=1, swt=0.5)
#' n <- 10
#' 
#' ## A R-rplba function
#' \dontrun{ 
#' rplba <- function(n, p=c(A=1.51, b=2.7, muv1=3.32, muv2=2.24, t_ND=0.08, 
#'                         muw1=1.51, muw2=3.69, t_delay=0.31, sv=1, swt=0.5)) 
#' {
#' require(msm)
#' ## Stage 1 LBA
#' v1 <- msm::rtnorm(n,p["muv1"],p["sv"],0); 
#' v2 <- msm::rtnorm(n,p["muv2"],p["sv"],0); 
#' sp <- matrix(runif(2*n,0,p["A"]),nrow=2)
#'     
#' ## Race
#' dt <- rbind((p["b"]-sp[1,])/v1,(p["b"]-sp[2,])/v2)
#' 
#' ## dt[dt<0] <- Inf
#' choice <- apply(dt,2,which.min)
#' rt <- dt[cbind(choice,1:n)]
#'     
#' ## Which are finished?
#' done <- rt <= p["swt"]
#' n2 <- sum(!done)
#'       
#' ## Distance left to travel for those not finished
#' B1 <- p["b"] - (sp[1,!done] + p["swt"]*v1[!done]) 
#' B2 <- p["b"] - (sp[2,!done] + p["swt"]*v2[!done]) 
#'         
#' ## Stage 2 LBA
#' w1 <- msm::rtnorm(n2,p["muw1"],p["sv"],0)
#' w2 <- msm::rtnorm(n2,p["muw2"],p["sv"],0)
#'           
#' ## Race  
#' dt <- rbind(B1/w1,B2/w2)
#' ## dt[dt<0] <- Inf
#' choice[!done] <- apply(dt,2,which.min)
#' rt[!done] <- p["swt"]+dt[cbind(choice[!done],1:n2)]
#'           
#' ## save results
#' cbind(choice=choice,rt=p["t_delay"]+rt)
#'             
#' }
#' }
#' 
#' system.time(DT1 <- rplba(n=1e2, p=pVec))
#' head(DT1)
#' 
#' \dontrun{
#' system.time(DT2 <- cpda::rplba(n=1e2, pVec=pVec))
#' head(DT2)
#' }
#' 
#' \dontrun{
#' ## Convert to data frame for plotting
#' tmp1 <- data.frame(choice=factor(DT1[,1]), dt=DT1[,2])
#' tmp2 <- data.frame(choice=factor(DT2[,1]), dt=DT2[,2])
#' summary(tmp1[tmp1$choice==1,])
#' summary(tmp2[tmp2$choice==1,])
#' 
#' summary(tmp1[tmp1$choice==2,])
#' summary(tmp2[tmp2$choice==2,])
#' 
#' tmp1$package <- "cpda"
#' tmp2$package <- "R"
#' tmp0 <- rbind(tmp1, tmp2)
#' tmp0$package <- factor(tmp0$package)
#' 
#' require(lattice)
#' lattice::histogram( ~ dt | package + choice, data = tmp0, aspect = 1,
#' xlab = "Decision Time (s)")
#'  
#' lattice::densityplot( ~ dt | package + choice, data = tmp0,   
#'          xlab = "Decisoin Time (s)", bw = stats::bw.nrd0(tmp0$dt))
#'}
rplba <- function(n, pVec) {
    .Call('cpda_rplba', PACKAGE = 'cpda', n, pVec)
}

#' @rdname rplba
#' @export
rplba_omp <- function(n, pVec) {
    .Call('cpda_rplba_omp', PACKAGE = 'cpda', n, pVec)
}

#' Retrieve Empirical Decision Times
#' 
#' This function only takes pLBA parameters and converts choice RTs to choice  
#' DTs in a matrix form. This is just a convenient function used interanlly by
#' \code{logLik_plba}. 
#'  
#' @param data a matrix with the first column stores choice (0==error; 
#' 1==correct), and the second column stores RTs in second.
#' @param pVec a vector storing pLBA model parameters. The sequence is 
#' critical. It is, A, b, muv1, muv2, t_ND, muw1, muw2, t_delay, sv, swt. 
#' See \code{\link{rplba}} for an explanation of the parameters.
#' @return A two-element list with decision time for accumulator 1 and 2.
#' @export
#' @examples
#' data(lba)
#' pVec <- c(A=1.51, b=2.7, muv1=3.32, muv2=2.24, t_ND=0.08, muw1=1.51,  
#'           muw2=3.69, t_delay=0.31,  sv=1, swt=0.5)
#'            
#' DTs <- cpda::choiceDT(data.matrix(d), pVec)
#'            
choiceDT <- function(data, pVec) {
    .Call('cpda_choiceDT', PACKAGE = 'cpda', data, pVec)
}

#' A simple and fast quantile calculator
#'
#' A C++ quantile function.
#'
#' @param y a data vector
#' @param q nth quantile. Enter proportion, such as .25 or .75.
#' @examples
#' y <- rnorm(100)
#' q <- cquantile(y, .25) 
#' @export
cquantile <- function(y, q) {
    .Call('cpda_cquantile', PACKAGE = 'cpda', y, q)
}

#' Silverman's Rule of Thumb Bandwidth for Kernel Density Estimation
#'
#' A C++ version of Silverman's rule-of-thumb bandwidth. This is similar
#' with R's \code{bw.nrd0(x)}
#'
#' @param y a data vector
#' @param m a multiplier to adjust the SROT proportionally.
#' 
#' @seealso
#' \code{\link{bw.nrd}}, \code{\link{bandwidth.nrd}}.
#' @export
#' @examples
#' data(lba)
#' h <-cpda::bwNRD0(plba$DT1, 0.8)
#' 
bwNRD0 <- function(y, m) {
    .Call('cpda_bwNRD0', PACKAGE = 'cpda', y, m)
}

